<?php
$posukiai= [
        [
                'kryptis'=>'desine',
                'laipsniai'=>90
        ],
        [
                'kryptis'=>'kaire',
                'laipsniai'=>20
        ],
        [
                'kryptis'=>'desine',
                'laipsniai'=>160
        ],
        [
                'kryptis'=>'kaire',
                'laipsniai'=>160
        ],
        [
                'kryptis'=>'desine',
                'laipsniai'=>180
        ],
        [
               'kryptis'=>'desine',
               'laipsniai'=>30
        ]
];
 var_dump($posukiai);

